affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - influxdb
        topologyKey: "kubernetes.io/hostname"

service:
  type: NodePort
  nodePort: 30002   # Porta externa para acesso ao InfluxDB
  ports:
    - name: http
      port: 8086       # Porta interna do InfluxDB
      targetPort: 8086
