auth:
  username: admin
  password: admin
  erlangCookie: secretcookie

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rabbitmq
        topologyKey: "kubernetes.io/hostname"

service:
  type: NodePort
  nodePorts:
    manager: 30001   # Painel de gerenciamento RabbitMQ (15672)
    amqp: 30003      # Porta AMQP (5672)

nodeSelector:
  kubernetes.io/hostname: iot-cluster-worker3

# initContainers:
#   - name: rabbitmq-setup
#     image: rabbitmq:3-management
#     command:
#       - "sh"
#       - "-c"
#       - |
#         rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbitmq.pid
#         rabbitmqadmin declare exchange name=fm.fanout type=fanout durable=true
#         rabbitmqadmin declare queue name=c durable=true
#         rabbitmqadmin declare queue name=p durable=true
#         rabbitmqadmin declare binding source=fm.fanout destination=c destination_type=queue
#         rabbitmqadmin declare binding source=fm.fanout destination=p destination_type=queue
#     env:
#       - name: RABBITMQ_DEFAULT_USER
#         value: "admin"
#       - name: RABBITMQ_DEFAULT_PASS
#         value: "admin"
#     volumeMounts:
#       - name: data-rabbitmq-0
#         mountPath: /var/lib/rabbitmq/mnesia

# volumes:
#   - name: data-rabbitmq-0
#     persistentVolumeClaim:
#       claimName: rabbitmq-pvc
