# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-container
        image: frankb227/consumer:1.6
        command: ["python3", "/scripts/receive-c.py"]
        resources:
          requests:
            cpu: "100m"    # Quantidade mínima de CPU necessária (100 milicores)
            memory: "128Mi" # Quantidade mínima de memória necessária
          limits:
            cpu: "500m"    # Limite máximo de CPU que pode ser usado
            memory: "256Mi" # Limite máximo de memória que pode ser usado
      nodeSelector: 
        kubernetes.io/hostname: iot-cluster-worker2

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer-app
spec:
  selector:
    app: consumer-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

