apiVersion: v1
kind: Pod
metadata:
  name: node-sensor-pod
  labels:
    app: node-sensor
spec:
  initContainers:
      - name: wait-for-influxdb
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 influxdb-service 8086; do echo "Waiting for InfluxDB..."; sleep 5; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 rabbitmq-service 5672; do echo "Waiting for RabbitMQ..."; sleep 5; done;']
  containers:
    - name: node-sensor
      image: mercydiniz/no-sensor:latest  # Imagem do Docker Hub
      env:
        - name: MAX_NODES
          value: "10"
        - name: INITIAL_NODES
          value: "2"
        - name: INFLUXDB_URL
          value: "http://influxdb-service:8086"
        - name: INFLUXDB_TOKEN
          value: "NwM3ta7vunbyUzySwxSgNMCRhGRYoHzGNY0yPap2nKvtYGNaMcarfp5_bvtKM85vTpXcXDffcGbputShx0v6ng=="
        - name: INFLUXDB_ORG
          value: "my-org"
        - name: BUCKET_NAME
          value: "sensor_data"
        - name: BROKER_URL
          value: "amqp://rabbitmq:rabbitmq@rabbitmq-service:5672"
        - name: EXCHANGE_NAME
          value: "fm.fanout"
  restartPolicy: Always
