apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10.5-management
        securityContext:
            runAsUser: 0
        ports:
        - containerPort: 5672
          name: messaging
        - containerPort: 15672
          name: management
        - containerPort: 25676
          name: clustering
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbitmq"
        volumeMounts:
        - name: script-volume
          mountPath: /scripts/setup_rabbitmq.sh
          subPath: setup_rabbitmq.sh
        command: ["sh", "-c", "/scripts/setup_rabbitmq.sh"]
      volumes:
      - name: script-volume
        configMap:
          name: rabbitmq-setup-script
          defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-setup-script
data:
  setup_rabbitmq.sh: |
    #!/bin/bash

    # Inicia o RabbitMQ em segundo plano
    rabbitmq-server &

    # Usuário e senha do RabbitMQ
    USER="rabbitmq"
    PASSWORD="rabbitmq"

    # URL do RabbitMQ Management API
    HOST="localhost"
    PORT="15672"

    # Aguarda o RabbitMQ inicializar
    echo "Aguardando RabbitMQ inicializar..."
    while true; do
      if grep -q "Server startup complete;" /var/log/rabbitmq/rabbit@$(hostname).log; then
        echo "RabbitMQ está pronto."
        break
      fi
      sleep 2
    done

    # Criando o exchange
    echo "Criando exchange 'fm.fanout'..."
    rabbitmqadmin -u $USER -p $PASSWORD declare exchange name=fm.fanout type=fanout durable=true

    # Criando as queues
    echo "Criando fila 'c'..."
    rabbitmqadmin -u $USER -p $PASSWORD declare queue name=c durable=true

    echo "Criando fila 'p'..."
    rabbitmqadmin -u $USER -p $PASSWORD declare queue name=p durable=true

    # Associando as queues ao exchange
    echo "Associando fila 'c' ao exchange 'fm.fanout'..."
    rabbitmqadmin -u $USER -p $PASSWORD declare binding source=fm.fanout destination=c destination_type=queue

    echo "Associando fila 'p' ao exchange 'fm.fanout'..."
    rabbitmqadmin -u $USER -p $PASSWORD declare binding source=fm.fanout destination=p destination_type=queue

    # Listando os bindings
    echo "Listando bindings..."
    rabbitmqadmin -u $USER -p $PASSWORD list bindings

    #Mantem o container em execução
    tail -f /dev/null

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: messaging
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: NodePort
